name: 4. Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "zensical.toml"

jobs:
  deploy:
    name: Publish Docs
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: {% raw %}${{ steps.deployment.outputs.page_url }}{% endraw %}
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "{{cookiecutter.python_version}}"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r ./requirements.txt
      - name: Build documentation
        run: |
          ./scripts/build.sh -c
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
        id: deployment
